#ifndef COLORCOMBOX_GLOBAL_H
#define COLORCOMBOX_GLOBAL_H

#include <QtCore/qglobal.h>

#if defined(COLORCOMBOX_LIBRARY)
#  define COLORCOMBOXSHARED_EXPORT Q_DECL_EXPORT
#else
#  define COLORCOMBOXSHARED_EXPORT Q_DECL_IMPORT
#endif

#endif // COLORCOMBOX_GLOBAL_H
